export const REAGISTER_REQUREST = "REAGISTER_REQUREST";
export const REAGISTER_SUCCESS = "REAGISTER_SUCCESS";
export const REAGISTER_FAILED = "REAGISTER_FAILED";

export const CHANGE_NUMBER_REQUEST = "CHANGE_NUMBER_REQUEST";
export const CHANGE_NUMBER_SUCCESS = "CHANGE_NUMBER_SUCCESS";
export const CHANGE_NUMBER_FAILD = "CHANGE_NUMBER_FAILD";

export const LOGIN_USER_REQUREST = "LOGIN_USER_REQUREST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

export const TOKEN_USER_REQUREST = "TOKEN_USER_REQUREST";
export const TOKEN_USER_SUCCESS = "TOKEN_USER_SUCCESS";
export const TOKEN_USER_FAILED = "TOKEN_USER_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";

export const PROFILE_UPDATE_SAUCCESS = "PROFILE_UPDATE_SAUCCESS";
export const PROFILE_FEATURED_SAUCCESS = "PROFILE_FEATURED_SAUCCESS";
export const PROFILE_PHOTO_SAUCCESS = "PROFILE_PHOTO_SAUCCESS";
export const COVER_PHOTO_SAUCCESS = "COVER_PHOTO_SAUCCESS";

export const GET_ALL_USER_REQ = "GET_ALL_USER_REQ";
export const GET_ALL_USERS_SAUCCESS = "GET_ALL_USERS_SAUCCESS";
export const GET_ALL_USERS_FAILD = "PROFILE_PHOTO_SAUCCESS";
export const GET_ALL_USERS = "GET_ALL_USERS";
